export const COUNTRIES = [
  "UAE", "USA", "Germany", "China", "Taiwan", "Japan", "South Korea", "Singapore", "Hong Kong", "Malaysia"
] as const;

export const CATEGORIES = [
  "Laptops - Windows Laptops",
  "Laptops - Apple Laptops",
  "Laptops - Chromebook Laptops",
  "Laptops - Laptop Bags",
  "Laptops - Laptop Chargers",
  "Laptops - Laptop Batteries",
  "Laptops - Laptop Stands/Coolers",
  "Laptops - Laptop Docking Stations",
  "Computers - Desktop Computers",
  "Computers - AIO (All-In-One Computers)",
  "Computers - Barebone Computers (NUC, Mini PC, Thin Client)",
  "Servers",
  "Servers - Server Components",
  "Servers - Server Accessories",
  "Phones/Tablets - Android Smartphones",
  "Phones/Tablets - Apple Smartphones",
  "Phones/Tablets - Android Tablets",
  "Phones/Tablets - Windows Tablets",
  "Phones/Tablets - Chromebook Tablets",
  "Phones/Tablets - Phone Accessories",
  "Electronics - Audio Equipment",
  "Electronics - Photo/Video Equipment",
  "Gadgets & Others - VR Headsets",
  "Gadgets & Others - Video Game Consoles",
  "Gadgets & Others - Wearables (Smart Watches/Bands)",
  "Gadgets & Others - Graphics Tablets",
  "Gadgets & Others - TV Boxes",
  "Gadgets & Others - Dash Cameras",
  "Gadgets & Others - E-Book Readers",
  "Gadgets & Others - Smart Home Devices",
  "Gadgets & Others - Electronic (Smart) Card Readers",
  "GPS Navigation Systems & Accessories",
  "PC Components - CPU (Intel)",
  "PC Components - CPU (AMD)",
  "PC Components - CPU (Server)",
  "PC Components - Thermal Paste",
  "PC Components - Motherboards (Intel)",
  "PC Components - Motherboards (AMD)",
  "PC Components - Motherboards (Server)",
  "PC Components - Graphics Cards (NVIDIA)",
  "PC Components - Graphics Cards (AMD)",
  "PC Components - Graphics Cards (Other)",
  "PC Components - RAM (DIMM)",
  "PC Components - RAM (SODIMM)",
  "PC Components - RAM (SERVER)",
  "PC Components - HDD",
  "PC Components - SSD",
  "PC Components - DVD-RW Drives",
  "PC Components - Cooling Systems (CPU Coolers)",
  "PC Components - Cooling Systems (Case Fans)",
  "PC Components - PC Cases (ATX)",
  "PC Components - PC Power Supplies (ATX)",
  "PC Components - Sound Cards",
  "PC Components - PCI/PCIe Cards",
  "Peripherals - Monitors",
  "Peripherals - Interactive Panels/Displays",
  "Peripherals - TVs",
  "Peripherals - Monitor/TV Mounts & Stands",
  "Peripherals - Printers, Copiers & Scanners",
  "Peripherals - Printer Consumables",
  "Peripherals - Projectors",
  "Peripherals - Projection Screens",
  "Peripherals - Projector Mounts & Tripods",
  "Peripherals - UPS & Batteries",
  "Peripherals - Surge Protectors",
  "Accessories - Keyboards",
  "Accessories - Mice",
  "Accessories - Mouse Pads",
  "Accessories - Speakers",
  "Accessories - Headphones",
  "Accessories - Microphones",
  "Accessories - Web Cameras",
  "Accessories - Gamepads/Joysticks/Steering Wheels",
  "Accessories - USB Flash Drives / Memory Cards (SD/CF etc.)",
  "Accessories - Card Readers",
  "Accessories - External HDD/SSD",
  "Accessories - External DVD",
  "Accessories - HDD/SSD/DVD Enclosures",
  "Accessories - Computer Cleaning Products",
  "Computer Furniture (Desks/Chairs)",
  "Software - Operating Systems",
  "Software - Other Software",
  "Cabling - Power Cables/Adapters",
  "Cabling - Storage & Data Cables/Adapters",
  "Cabling - Video Cables/Adapters",
  "Cabling - Audio Cables/Adapters",
  "Cabling - Network Cables/Adapters",
  "Networking - Routers",
  "Networking - Switches",
  "Networking - Network Adapters (LAN/Wi-Fi)",
  "Networking - NAS Systems",
  "Networking - Tools",
  "Inventory Management & POS Systems - Barcode Scanners",
  "Inventory Management & POS Systems - Label/Receipt Printers",
  "Inventory Management & POS Systems - POS Equipment",
  "Inventory Management & POS Systems - Data Collection Terminals",
  "Inventory Management & POS Systems - Cash Drawers",
  "Inventory Management & POS Systems - Scales",
  "Inventory Management & POS Systems - Labels/Paper & Consumables",
  "Security Systems - Video Surveillance",
  "Security Systems - Fire Suppression Systems",
  "Photo/Video Equipment & Accessories"
] as const;

export const BRANDS = [
  "Access IS",
  "Acer",
  "Adaptec",
  "ADATA",
  "Adder Technology",
  "Alienware",
  "Amazon",
  "AMD",
  "Anker",
  "Ant Esports",
  "Antec",
  "AOpen",
  "Aorus",
  "APC",
  "Apple",
  "Arctic",
  "ASKEY",
  "ASRock",
  "ASUS",
  "ASUSTOR",
  "Be Quiet!",
  "Belkin",
  "BenQ",
  "Biostar",
  "Broadcom",
  "Brother Industries",
  "Cable Matters",
  "Canon",
  "CaseLabs (legacy)",
  "Cherry",
  "Chicony Electronics",
  "Cisco",
  "Cooler Master",
  "Corsair",
  "Creative",
  "Crucial",
  "CyberPowerPC",
  "Deepcool",
  "Dell",
  "D-Link",
  "Dynabook",
  "Eaton",
  "Eizo",
  "EKWB",
  "ELSA Technology",
  "Epson",
  "EVGA",
  "Falcon Northwest",
  "Fellowes",
  "Fender",
  "Fluke",
  "Focusrite",
  "Fortinet",
  "Fractal Design",
  "Framework",
  "Fujitsu",
  "G.SKILL",
  "Gainward",
  "Gigabyte",
  "Google",
  "Hikvision",
  "HIS",
  "Hisense",
  "Honeywell",
  "Honor",
  "HP",
  "HPE",
  "Huawei",
  "HyperX",
  "IBM",
  "iBUYPOWER",
  "Iiyama",
  "iKey",
  "Inno3D",
  "Integra Sources",
  "Intel",
  "Jabra",
  "JBL",
  "Kingston",
  "Kioxia",
  "Lacie",
  "Lenovo",
  "Lexar",
  "Lexmark",
  "LG",
  "Lian Li",
  "Linksys",
  "Lite-On",
  "Logitech",
  "LSI",
  "MagicSilicon",
  "Makita",
  "Maxell",
  "Mellanox",
  "Micron",
  "Microsoft",
  "Mikrotik",
  "Motorola",
  "MSI",
  "NavePoint",
  "NEC",
  "Netgear",
  "Noctua",
  "Nothing",
  "NVIDIA",
  "NZXT",
  "OCZ Technology",
  "Olympus",
  "OnePlus",
  "OPPO",
  "Oracle",
  "Origin PC",
  "OtterBox",
  "OWC (Other World Computing)",
  "Panasonic",
  "Patriot",
  "Phanteks",
  "Philips",
  "Pimax",
  "Planar Systems",
  "Plantronics",
  "PNY",
  "PowerColor",
  "QNAP",
  "Razer",
  "Realme",
  "Realtek",
  "Roccat",
  "Roland",
  "Samsung",
  "SanDisk",
  "Sapphire",
  "Seagate",
  "Seasonic",
  "Sennheiser",
  "Sharp",
  "Shure",
  "Silicon Power",
  "SilverStone",
  "Sonos",
  "Sony",
  "SoundMAGIC",
  "Spigen",
  "SteelSeries",
  "Supermicro",
  "Synaptics",
  "Synology",
  "System76",
  "Thermaltake",
  "Toshiba",
  "TP-Link",
  "Transcend",
  "TRENDnet",
  "Tripp Lite",
  "Ubiquiti",
  "Valve",
  "Vertiv / Delta",
  "ViewSonic",
  "Vivo",
  "Western Digital (WD)",
  "Xerox",
  "XFX",
  "Xiaomi",
  "XPG (ADATA)",
  "ZOTAC"
] as const;

export const WORKING_STYLES = [
  "B2B", "PRICE-LISTS", "INQUIRIES"
] as const;

export type Country = typeof COUNTRIES[number];
export type Category = typeof CATEGORIES[number];
export type Brand = typeof BRANDS[number];
export type WorkingStyle = typeof WORKING_STYLES[number];

export interface SearchFilters {
  query?: string;
  country?: string;
  category?: string;
  brand?: string;
  minReputation?: number;
  workingStyle?: string;
}

export interface SupplierWithMatches {
  id: number;
  name: string;
  country: string;
  reputation: number;
  categories: string[];
  brands: string[];
  workingStyle: string[];
  matches?: string[];
}
